version: "3"
services:
  db:
    container_name: devopsdb
    build: ./Docker-db
    ports:
      - "3306:3306"

  app:
    container_name: devopsapp
    build: ./Docker-app
    ports:
      - "3307:8080"
    depends_on:
      - db
